version: '2'

services:
  transmission:
    build:
      context: .
      dockerfile: Dockerfile
    image: stiles/docker-transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/data
    env_file: 
      - ./common.env

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: stiles/docker-transmission-openvpn-proxy
    links:
      - transmission
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
